#!/usr/bin/env python3
# Emit simd_quad_pi5_spine_family.{h,c} with one compile-time-N specialization
# of the Pi 5 (Cortex-A76) general-n spine descent per N in
# pi5_runs/sweep_n_list.txt.
#
# Same shape as gen_m4_spine_family.py (CLAUDE.md decision 2026-05-19): naive
# constant-prop unroll of the general-n descent (3 quat -> binary tail ->
# final-lo). NOT the shipping hybrid at N=4096 -- a self-consistent F* shape
# isolates the constant-prop value from the hybrid finish value.
#
# Pi 5 deltas vs the M4 codegen:
#   - gap = 32 (one A76 64-byte cache line) instead of 64.
#   - block check uses paired vld1q_u16_x2 + 4-way OR, matching simd_quad_pi5.
#   - spine sweep below n=64 (gap floor on M4) is replaced by n<32 here:
#     pi5_runs/sweep_n_list.txt starts at 64 to match the M4 list, so this
#     codegen never hits the cardinality<gap path.
#
# Tail sweep after num_blocks*gap is included for N % gap != 0.

import os, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SWEEP = os.path.join(ROOT, "pi5_runs", "sweep_n_list.txt")

with open(SWEEP) as f:
    NS = [int(x) for x in f.read().split()]

GAP = 32
assert all(n >= GAP for n in NS), "sweep list must respect n>=gap floor"
assert len(set(NS)) == len(NS), "sweep list must be unique"

HEADER = """// AUTO-GENERATED by gen_pi5_spine_family.py. Do not edit by hand.
//
// Compile-time-N specializations of simd_quad_pi5_spine for the F* sweep.
// Naive constant-prop unroll of the general-n descent (3 quat -> binary
// tail -> final-lo). Not the hybrid; see CLAUDE.md / KMtrick for the
// shipping hybrid at N=4096.
//
// Build alongside bench_sweep.cpp (with -DQUADSEARCH_ARM_PI5).
#pragma once
#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

"""

FOOTER_H = """
bool simd_quad_pi5_spineN_dispatch(const uint16_t *carr, const uint16_t *spine,
                                   int32_t n, uint16_t pos);

#ifdef __cplusplus
}
#endif
"""

C_PROLOGUE = """// AUTO-GENERATED by gen_pi5_spine_family.py. Do not edit by hand.
#include <stdbool.h>
#include <stdint.h>
#include <arm_neon.h>

// Body shared by every specialization. num_blocks is a compile-time constant,
// so the compiler fully unrolls the descent (the while loops have static trip
// counts derived from num_blocks). gap is fixed at 32 (Pi 5 / Cortex-A76
// 64-byte cache line).
//
// The shape mirrors simd_quad_pi5_spine in simd_quad_pi5.c:
//   - quaternary descent while n > 3
//   - binary tail while n > 1
//   - final-lo branchless pick
//   - block-load + 4x vceqq_u16 against carr[lo*gap .. lo*gap+31]
//
// Tail sweep after num_blocks*gap is included for N % gap != 0.
#define SIMD_QUAD_PI5_SPINE_BODY(NUM_BLOCKS, CARDINALITY)                      \\
    do {                                                                       \\
        enum { gap = 32, num_blocks = (NUM_BLOCKS), cardinality = (CARDINALITY) }; \\
        __builtin_prefetch(spine);                                             \\
        int32_t base = 0;                                                      \\
        int32_t n = num_blocks;                                                \\
        while (n > 3) {                                                        \\
            int32_t quarter = n >> 2;                                          \\
            int32_t k1 = spine[base + quarter];                                \\
            int32_t k2 = spine[base + 2 * quarter];                            \\
            int32_t k3 = spine[base + 3 * quarter];                            \\
            int32_t c1 = (k1 < pos);                                           \\
            int32_t c2 = (k2 < pos);                                           \\
            int32_t c3 = (k3 < pos);                                           \\
            base += (c1 + c2 + c3) * quarter;                                  \\
            n -= 3 * quarter;                                                  \\
        }                                                                      \\
        while (n > 1) {                                                        \\
            int32_t half = n >> 1;                                             \\
            base = (spine[base + half] < pos) ? base + half : base;            \\
            n -= half;                                                         \\
        }                                                                      \\
        int32_t lo = (spine[base] < pos) ? base + 1 : base;                    \\
        if (lo < num_blocks) {                                                 \\
            const uint16_t *blk = carr + lo * gap;                             \\
            uint16x8_t needle = vdupq_n_u16(pos);                              \\
            uint16x8x2_t a = vld1q_u16_x2(blk);                                \\
            uint16x8x2_t b = vld1q_u16_x2(blk + 16);                           \\
            uint16x8_t h0 = vceqq_u16(a.val[0], needle);                       \\
            uint16x8_t h1 = vceqq_u16(a.val[1], needle);                       \\
            uint16x8_t h2 = vceqq_u16(b.val[0], needle);                       \\
            uint16x8_t h3 = vceqq_u16(b.val[1], needle);                       \\
            uint16x8_t hit = vorrq_u16(vorrq_u16(h0, h1), vorrq_u16(h2, h3));  \\
            return vmaxvq_u16(hit) != 0;                                       \\
        }                                                                      \\
        for (int32_t j = num_blocks * gap; j < cardinality; j++) {             \\
            uint16_t v = carr[j];                                              \\
            if (v >= pos) return v == pos;                                     \\
        }                                                                      \\
        return false;                                                          \\
    } while (0)

"""

def main():
    h_lines = [HEADER]
    c_lines = [C_PROLOGUE]

    for n in NS:
        num_blocks = n // GAP
        h_lines.append(
            f"bool simd_quad_pi5_spineN_{n}(const uint16_t *carr,\n"
            f"                            const uint16_t *spine,\n"
            f"                            uint16_t pos);\n"
        )
        c_lines.append(
            f"bool simd_quad_pi5_spineN_{n}(const uint16_t *carr,\n"
            f"                            const uint16_t *spine,\n"
            f"                            uint16_t pos) {{\n"
            f"    SIMD_QUAD_PI5_SPINE_BODY({num_blocks}, {n});\n"
            f"}}\n\n"
        )

    c_lines.append(
        "bool simd_quad_pi5_spineN_dispatch(const uint16_t *carr,\n"
        "                                   const uint16_t *spine,\n"
        "                                   int32_t n, uint16_t pos) {\n"
        "    switch (n) {\n"
    )
    for n in NS:
        c_lines.append(f"        case {n}: return simd_quad_pi5_spineN_{n}(carr, spine, pos);\n")
    c_lines.append(
        "        default:\n"
        "            // unreachable; the sweep driver only invokes listed N.\n"
        "            __builtin_trap();\n"
        "    }\n"
        "}\n"
    )

    h_lines.append(FOOTER_H)

    with open(os.path.join(ROOT, "simd_quad_pi5_spine_family.h"), "w") as f:
        f.write("".join(h_lines))
    with open(os.path.join(ROOT, "simd_quad_pi5_spine_family.c"), "w") as f:
        f.write("".join(c_lines))

    print(f"emitted {len(NS)} specializations: {NS[0]} .. {NS[-1]}")

if __name__ == "__main__":
    main()
