// AUTO-GENERATED by gen_m4_spine_family.py. Do not edit by hand.
#include <stdbool.h>
#include <stdint.h>
#include <arm_neon.h>

// Body shared by every specialization. num_blocks is a compile-time constant,
// so the compiler fully unrolls the descent (the while loops have static trip
// counts derived from num_blocks). gap is fixed at 64 (M4 cache line).
//
// The shape mirrors simd_quad_m4_spine in simd_quad_m4.c:
//   - quaternary descent while n > 3
//   - binary tail while n > 1
//   - final-lo branchless pick
//   - block-load + 8x vceqq_u16 against carr[lo*gap .. lo*gap+63]
//
// Tail sweep after num_blocks*gap is included for N % gap != 0.
#define SIMD_QUAD_M4_SPINE_BODY(NUM_BLOCKS, CARDINALITY)                       \
    do {                                                                       \
        enum { gap = 64, num_blocks = (NUM_BLOCKS), cardinality = (CARDINALITY) }; \
        __builtin_prefetch(spine);                                             \
        int32_t base = 0;                                                      \
        int32_t n = num_blocks;                                                \
        while (n > 3) {                                                        \
            int32_t quarter = n >> 2;                                          \
            int32_t k1 = spine[base + quarter];                                \
            int32_t k2 = spine[base + 2 * quarter];                            \
            int32_t k3 = spine[base + 3 * quarter];                            \
            int32_t c1 = (k1 < pos);                                           \
            int32_t c2 = (k2 < pos);                                           \
            int32_t c3 = (k3 < pos);                                           \
            base += (c1 + c2 + c3) * quarter;                                  \
            n -= 3 * quarter;                                                  \
        }                                                                      \
        while (n > 1) {                                                        \
            int32_t half = n >> 1;                                             \
            base = (spine[base + half] < pos) ? base + half : base;            \
            n -= half;                                                         \
        }                                                                      \
        int32_t lo = (spine[base] < pos) ? base + 1 : base;                    \
        if (lo < num_blocks) {                                                 \
            const uint16_t *blk = carr + lo * gap;                             \
            uint16x8_t needle = vdupq_n_u16(pos);                              \
            uint16x8x4_t a = vld1q_u16_x4(blk);                                \
            uint16x8x4_t b = vld1q_u16_x4(blk + 32);                           \
            uint16x8_t h0 = vorrq_u16(                                         \
                vorrq_u16(vceqq_u16(a.val[0], needle), vceqq_u16(a.val[1], needle)), \
                vorrq_u16(vceqq_u16(a.val[2], needle), vceqq_u16(a.val[3], needle))); \
            uint16x8_t h1 = vorrq_u16(                                         \
                vorrq_u16(vceqq_u16(b.val[0], needle), vceqq_u16(b.val[1], needle)), \
                vorrq_u16(vceqq_u16(b.val[2], needle), vceqq_u16(b.val[3], needle))); \
            return vmaxvq_u16(vorrq_u16(h0, h1)) != 0;                         \
        }                                                                      \
        for (int32_t j = num_blocks * gap; j < cardinality; j++) {             \
            uint16_t v = carr[j];                                              \
            if (v >= pos) return v == pos;                                     \
        }                                                                      \
        return false;                                                          \
    } while (0)

bool simd_quad_m4_spineN_64(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(1, 64);
}

bool simd_quad_m4_spineN_67(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(1, 67);
}

bool simd_quad_m4_spineN_70(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(1, 70);
}

bool simd_quad_m4_spineN_74(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(1, 74);
}

bool simd_quad_m4_spineN_77(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(1, 77);
}

bool simd_quad_m4_spineN_81(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(1, 81);
}

bool simd_quad_m4_spineN_85(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(1, 85);
}

bool simd_quad_m4_spineN_89(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(1, 89);
}

bool simd_quad_m4_spineN_93(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(1, 93);
}

bool simd_quad_m4_spineN_98(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(1, 98);
}

bool simd_quad_m4_spineN_102(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(1, 102);
}

bool simd_quad_m4_spineN_107(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(1, 107);
}

bool simd_quad_m4_spineN_113(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(1, 113);
}

bool simd_quad_m4_spineN_118(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(1, 118);
}

bool simd_quad_m4_spineN_124(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(1, 124);
}

bool simd_quad_m4_spineN_130(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(2, 130);
}

bool simd_quad_m4_spineN_136(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(2, 136);
}

bool simd_quad_m4_spineN_143(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(2, 143);
}

bool simd_quad_m4_spineN_150(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(2, 150);
}

bool simd_quad_m4_spineN_157(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(2, 157);
}

bool simd_quad_m4_spineN_164(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(2, 164);
}

bool simd_quad_m4_spineN_172(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(2, 172);
}

bool simd_quad_m4_spineN_181(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(2, 181);
}

bool simd_quad_m4_spineN_189(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(2, 189);
}

bool simd_quad_m4_spineN_199(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(3, 199);
}

bool simd_quad_m4_spineN_208(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(3, 208);
}

bool simd_quad_m4_spineN_218(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(3, 218);
}

bool simd_quad_m4_spineN_229(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(3, 229);
}

bool simd_quad_m4_spineN_240(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(3, 240);
}

bool simd_quad_m4_spineN_252(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(3, 252);
}

bool simd_quad_m4_spineN_264(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(4, 264);
}

bool simd_quad_m4_spineN_277(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(4, 277);
}

bool simd_quad_m4_spineN_290(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(4, 290);
}

bool simd_quad_m4_spineN_304(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(4, 304);
}

bool simd_quad_m4_spineN_319(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(4, 319);
}

bool simd_quad_m4_spineN_334(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(5, 334);
}

bool simd_quad_m4_spineN_350(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(5, 350);
}

bool simd_quad_m4_spineN_367(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(5, 367);
}

bool simd_quad_m4_spineN_385(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(6, 385);
}

bool simd_quad_m4_spineN_403(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(6, 403);
}

bool simd_quad_m4_spineN_423(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(6, 423);
}

bool simd_quad_m4_spineN_443(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(6, 443);
}

bool simd_quad_m4_spineN_465(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(7, 465);
}

bool simd_quad_m4_spineN_487(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(7, 487);
}

bool simd_quad_m4_spineN_511(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(7, 511);
}

bool simd_quad_m4_spineN_535(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(8, 535);
}

bool simd_quad_m4_spineN_561(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(8, 561);
}

bool simd_quad_m4_spineN_588(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(9, 588);
}

bool simd_quad_m4_spineN_617(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(9, 617);
}

bool simd_quad_m4_spineN_647(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(10, 647);
}

bool simd_quad_m4_spineN_678(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(10, 678);
}

bool simd_quad_m4_spineN_711(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(11, 711);
}

bool simd_quad_m4_spineN_745(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(11, 745);
}

bool simd_quad_m4_spineN_781(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(12, 781);
}

bool simd_quad_m4_spineN_819(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(12, 819);
}

bool simd_quad_m4_spineN_858(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(13, 858);
}

bool simd_quad_m4_spineN_899(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(14, 899);
}

bool simd_quad_m4_spineN_943(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(14, 943);
}

bool simd_quad_m4_spineN_988(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(15, 988);
}

bool simd_quad_m4_spineN_1036(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(16, 1036);
}

bool simd_quad_m4_spineN_1086(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(16, 1086);
}

bool simd_quad_m4_spineN_1138(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(17, 1138);
}

bool simd_quad_m4_spineN_1193(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(18, 1193);
}

bool simd_quad_m4_spineN_1251(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(19, 1251);
}

bool simd_quad_m4_spineN_1311(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(20, 1311);
}

bool simd_quad_m4_spineN_1374(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(21, 1374);
}

bool simd_quad_m4_spineN_1441(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(22, 1441);
}

bool simd_quad_m4_spineN_1510(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(23, 1510);
}

bool simd_quad_m4_spineN_1583(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(24, 1583);
}

bool simd_quad_m4_spineN_1659(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(25, 1659);
}

bool simd_quad_m4_spineN_1739(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(27, 1739);
}

bool simd_quad_m4_spineN_1823(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(28, 1823);
}

bool simd_quad_m4_spineN_1911(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(29, 1911);
}

bool simd_quad_m4_spineN_2003(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(31, 2003);
}

bool simd_quad_m4_spineN_2100(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(32, 2100);
}

bool simd_quad_m4_spineN_2201(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(34, 2201);
}

bool simd_quad_m4_spineN_2307(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(36, 2307);
}

bool simd_quad_m4_spineN_2418(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(37, 2418);
}

bool simd_quad_m4_spineN_2535(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(39, 2535);
}

bool simd_quad_m4_spineN_2657(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(41, 2657);
}

bool simd_quad_m4_spineN_2785(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(43, 2785);
}

bool simd_quad_m4_spineN_2920(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(45, 2920);
}

bool simd_quad_m4_spineN_3061(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(47, 3061);
}

bool simd_quad_m4_spineN_3208(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(50, 3208);
}

bool simd_quad_m4_spineN_3363(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(52, 3363);
}

bool simd_quad_m4_spineN_3525(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(55, 3525);
}

bool simd_quad_m4_spineN_3695(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(57, 3695);
}

bool simd_quad_m4_spineN_3873(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(60, 3873);
}

bool simd_quad_m4_spineN_4060(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(63, 4060);
}

bool simd_quad_m4_spineN_4096(const uint16_t *carr,
                           const uint16_t *spine,
                           uint16_t pos) {
    SIMD_QUAD_M4_SPINE_BODY(64, 4096);
}

bool simd_quad_m4_spineN_dispatch(const uint16_t *carr,
                                  const uint16_t *spine,
                                  int32_t n, uint16_t pos) {
    switch (n) {
        case 64: return simd_quad_m4_spineN_64(carr, spine, pos);
        case 67: return simd_quad_m4_spineN_67(carr, spine, pos);
        case 70: return simd_quad_m4_spineN_70(carr, spine, pos);
        case 74: return simd_quad_m4_spineN_74(carr, spine, pos);
        case 77: return simd_quad_m4_spineN_77(carr, spine, pos);
        case 81: return simd_quad_m4_spineN_81(carr, spine, pos);
        case 85: return simd_quad_m4_spineN_85(carr, spine, pos);
        case 89: return simd_quad_m4_spineN_89(carr, spine, pos);
        case 93: return simd_quad_m4_spineN_93(carr, spine, pos);
        case 98: return simd_quad_m4_spineN_98(carr, spine, pos);
        case 102: return simd_quad_m4_spineN_102(carr, spine, pos);
        case 107: return simd_quad_m4_spineN_107(carr, spine, pos);
        case 113: return simd_quad_m4_spineN_113(carr, spine, pos);
        case 118: return simd_quad_m4_spineN_118(carr, spine, pos);
        case 124: return simd_quad_m4_spineN_124(carr, spine, pos);
        case 130: return simd_quad_m4_spineN_130(carr, spine, pos);
        case 136: return simd_quad_m4_spineN_136(carr, spine, pos);
        case 143: return simd_quad_m4_spineN_143(carr, spine, pos);
        case 150: return simd_quad_m4_spineN_150(carr, spine, pos);
        case 157: return simd_quad_m4_spineN_157(carr, spine, pos);
        case 164: return simd_quad_m4_spineN_164(carr, spine, pos);
        case 172: return simd_quad_m4_spineN_172(carr, spine, pos);
        case 181: return simd_quad_m4_spineN_181(carr, spine, pos);
        case 189: return simd_quad_m4_spineN_189(carr, spine, pos);
        case 199: return simd_quad_m4_spineN_199(carr, spine, pos);
        case 208: return simd_quad_m4_spineN_208(carr, spine, pos);
        case 218: return simd_quad_m4_spineN_218(carr, spine, pos);
        case 229: return simd_quad_m4_spineN_229(carr, spine, pos);
        case 240: return simd_quad_m4_spineN_240(carr, spine, pos);
        case 252: return simd_quad_m4_spineN_252(carr, spine, pos);
        case 264: return simd_quad_m4_spineN_264(carr, spine, pos);
        case 277: return simd_quad_m4_spineN_277(carr, spine, pos);
        case 290: return simd_quad_m4_spineN_290(carr, spine, pos);
        case 304: return simd_quad_m4_spineN_304(carr, spine, pos);
        case 319: return simd_quad_m4_spineN_319(carr, spine, pos);
        case 334: return simd_quad_m4_spineN_334(carr, spine, pos);
        case 350: return simd_quad_m4_spineN_350(carr, spine, pos);
        case 367: return simd_quad_m4_spineN_367(carr, spine, pos);
        case 385: return simd_quad_m4_spineN_385(carr, spine, pos);
        case 403: return simd_quad_m4_spineN_403(carr, spine, pos);
        case 423: return simd_quad_m4_spineN_423(carr, spine, pos);
        case 443: return simd_quad_m4_spineN_443(carr, spine, pos);
        case 465: return simd_quad_m4_spineN_465(carr, spine, pos);
        case 487: return simd_quad_m4_spineN_487(carr, spine, pos);
        case 511: return simd_quad_m4_spineN_511(carr, spine, pos);
        case 535: return simd_quad_m4_spineN_535(carr, spine, pos);
        case 561: return simd_quad_m4_spineN_561(carr, spine, pos);
        case 588: return simd_quad_m4_spineN_588(carr, spine, pos);
        case 617: return simd_quad_m4_spineN_617(carr, spine, pos);
        case 647: return simd_quad_m4_spineN_647(carr, spine, pos);
        case 678: return simd_quad_m4_spineN_678(carr, spine, pos);
        case 711: return simd_quad_m4_spineN_711(carr, spine, pos);
        case 745: return simd_quad_m4_spineN_745(carr, spine, pos);
        case 781: return simd_quad_m4_spineN_781(carr, spine, pos);
        case 819: return simd_quad_m4_spineN_819(carr, spine, pos);
        case 858: return simd_quad_m4_spineN_858(carr, spine, pos);
        case 899: return simd_quad_m4_spineN_899(carr, spine, pos);
        case 943: return simd_quad_m4_spineN_943(carr, spine, pos);
        case 988: return simd_quad_m4_spineN_988(carr, spine, pos);
        case 1036: return simd_quad_m4_spineN_1036(carr, spine, pos);
        case 1086: return simd_quad_m4_spineN_1086(carr, spine, pos);
        case 1138: return simd_quad_m4_spineN_1138(carr, spine, pos);
        case 1193: return simd_quad_m4_spineN_1193(carr, spine, pos);
        case 1251: return simd_quad_m4_spineN_1251(carr, spine, pos);
        case 1311: return simd_quad_m4_spineN_1311(carr, spine, pos);
        case 1374: return simd_quad_m4_spineN_1374(carr, spine, pos);
        case 1441: return simd_quad_m4_spineN_1441(carr, spine, pos);
        case 1510: return simd_quad_m4_spineN_1510(carr, spine, pos);
        case 1583: return simd_quad_m4_spineN_1583(carr, spine, pos);
        case 1659: return simd_quad_m4_spineN_1659(carr, spine, pos);
        case 1739: return simd_quad_m4_spineN_1739(carr, spine, pos);
        case 1823: return simd_quad_m4_spineN_1823(carr, spine, pos);
        case 1911: return simd_quad_m4_spineN_1911(carr, spine, pos);
        case 2003: return simd_quad_m4_spineN_2003(carr, spine, pos);
        case 2100: return simd_quad_m4_spineN_2100(carr, spine, pos);
        case 2201: return simd_quad_m4_spineN_2201(carr, spine, pos);
        case 2307: return simd_quad_m4_spineN_2307(carr, spine, pos);
        case 2418: return simd_quad_m4_spineN_2418(carr, spine, pos);
        case 2535: return simd_quad_m4_spineN_2535(carr, spine, pos);
        case 2657: return simd_quad_m4_spineN_2657(carr, spine, pos);
        case 2785: return simd_quad_m4_spineN_2785(carr, spine, pos);
        case 2920: return simd_quad_m4_spineN_2920(carr, spine, pos);
        case 3061: return simd_quad_m4_spineN_3061(carr, spine, pos);
        case 3208: return simd_quad_m4_spineN_3208(carr, spine, pos);
        case 3363: return simd_quad_m4_spineN_3363(carr, spine, pos);
        case 3525: return simd_quad_m4_spineN_3525(carr, spine, pos);
        case 3695: return simd_quad_m4_spineN_3695(carr, spine, pos);
        case 3873: return simd_quad_m4_spineN_3873(carr, spine, pos);
        case 4060: return simd_quad_m4_spineN_4060(carr, spine, pos);
        case 4096: return simd_quad_m4_spineN_4096(carr, spine, pos);
        default:
            // unreachable; the sweep driver only invokes listed N.
            // abort loudly rather than returning a wrong answer.
            __builtin_trap();
    }
}
