// AUTO-GENERATED by gen_pi5_spine_family.py. Do not edit by hand.
//
// Compile-time-N specializations of simd_quad_pi5_spine for the F* sweep.
// Naive constant-prop unroll of the general-n descent (3 quat -> binary
// tail -> final-lo). Not the hybrid; see CLAUDE.md / KMtrick for the
// shipping hybrid at N=4096.
//
// Build alongside bench_sweep.cpp (with -DQUADSEARCH_ARM_PI5).
#pragma once
#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

bool simd_quad_pi5_spineN_64(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_67(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_70(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_74(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_77(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_81(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_85(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_89(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_93(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_98(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_102(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_107(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_113(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_118(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_124(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_130(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_136(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_143(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_150(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_157(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_164(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_172(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_181(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_189(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_199(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_208(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_218(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_229(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_240(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_252(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_264(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_277(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_290(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_304(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_319(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_334(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_350(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_367(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_385(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_403(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_423(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_443(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_465(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_487(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_511(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_535(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_561(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_588(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_617(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_647(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_678(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_711(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_745(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_781(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_819(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_858(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_899(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_943(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_988(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_1036(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_1086(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_1138(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_1193(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_1251(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_1311(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_1374(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_1441(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_1510(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_1583(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_1659(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_1739(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_1823(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_1911(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_2003(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_2100(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_2201(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_2307(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_2418(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_2535(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_2657(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_2785(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_2920(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_3061(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_3208(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_3363(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_3525(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_3695(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_3873(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_4060(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);
bool simd_quad_pi5_spineN_4096(const uint16_t *carr,
                            const uint16_t *spine,
                            uint16_t pos);

bool simd_quad_pi5_spineN_dispatch(const uint16_t *carr, const uint16_t *spine,
                                   int32_t n, uint16_t pos);

#ifdef __cplusplus
}
#endif
